name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment when changes are pushed to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the React app
      - name: Build the app
        run: npm run build

      # Install gh-pages globally
      - name: Install gh-pages
        run: npm install -g gh-pages

      # configure user  
      - name: Configure Git user
        run: |
          git config --global user.email "${{ secrets.GIT_CONFIG_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_CONFIG_NAME }}"
          git config --global url.https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/.insteadOf https://github.com/
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
